import cron from 'node-cron'
import Tenant from '../models/Tenant.model.js'
import Bill from '../models/Bill.model.js'
import Property from '../models/Property.model.js'
import LandlordProfile from '../models/LandlordProfile.model.js'
import { sendBillReadyNotification } from '../services/notification.service.js'
import { getPlanConfig } from '../utils/plans.js'

const BILLING_TIMEZONE = process.env.BILLING_TIMEZONE || 'Asia/Dhaka'

const getBillingDateParts = (date = new Date()) => {
  const formatter = new Intl.DateTimeFormat('en-CA', {
    timeZone: BILLING_TIMEZONE,
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
  })

  const parts = formatter
    .formatToParts(date)
    .reduce((acc, part) => {
      if (part.type !== 'literal') acc[part.type] = part.value
      return acc
    }, {})

  return {
    year: Number(parts.year),
    monthNumber: Number(parts.month),
    dayOfMonth: Number(parts.day),
    month: `${parts.year}-${parts.month}`,
  }
}

export const runBillGenerationJob = async () => {
  const { dayOfMonth, year, monthNumber, month } = getBillingDateParts()

  console.log(`⏰ Auto bill check — day ${dayOfMonth}, month ${month}, tz ${BILLING_TIMEZONE}`)

  try {
    const profiles = await LandlordProfile.find({ billGenerationDay: dayOfMonth })
    if (profiles.length === 0) return

    let totalCreated = 0
    let totalSkipped = 0

    for (const profile of profiles) {
      const plan = await getPlanConfig(profile.plan)
      if (!plan.autoBill) continue

      const landlordId = profile.userId
      const dueDateDay = dayOfMonth + (profile.billDueDays || 10)
      const dueDate = new Date(year, monthNumber - 1, Math.min(dueDateDay, 28))

      const tenantFilter = { landlordId, isActive: true }
      if (profile.autoBillPropertyName) {
        const properties = await Property.find({
          landlordId,
          propertyName: profile.autoBillPropertyName,
        }).select('_id')
        tenantFilter.propertyId = { $in: properties.map((property) => property._id) }
      }

      const tenants = await Tenant.find(tenantFilter)
        .populate('propertyId')
        .populate('userId')

      for (const tenant of tenants) {
        const existing = await Bill.findOne({ tenantId: tenant._id, month })
        if (existing) {
          totalSkipped++
          continue
        }

        const rentAmount = tenant.monthlyRent || tenant.propertyId?.monthlyRent || 0
        const items = [{ type: 'rent', amount: rentAmount }]

        const ud = tenant.utilityDefaults || {}
        if (ud.gasAmount > 0) items.push({ type: 'gas', label: 'গ্যাস বিল', amount: ud.gasAmount })
        if (ud.waterAmount > 0) items.push({ type: 'water', label: 'পানির বিল', amount: ud.waterAmount })
        if (ud.serviceCharge > 0) items.push({ type: 'maintenance', label: 'সার্ভিস চার্জ', amount: ud.serviceCharge })
        if (ud.garbageAmount > 0) items.push({ type: 'garbage', label: 'ময়লার বিল', amount: ud.garbageAmount })
        if (ud.electricityAmount > 0) items.push({ type: 'electricity', label: 'বিদ্যুৎ বিল', amount: ud.electricityAmount })

        const totalAmount = items.reduce((s, i) => s + i.amount, 0)

        const bill = await Bill.create({
          landlordId,
          tenantId: tenant._id,
          propertyId: tenant.propertyId._id,
          month,
          year,
          items,
          totalAmount,
          dueAmount: totalAmount,
          dueDate,
          isAutoGenerated: true,
        })

        await sendBillReadyNotification(tenant, bill)
        totalCreated++
      }
    }

    console.log(`✅ Auto bill generation done — Created: ${totalCreated}, Skipped: ${totalSkipped}`)
  } catch (err) {
    console.error('❌ Bill generation job failed:', err.message)
  }
}

export const startBillGenerationJob = () => {
  // Run every hour in Bangladesh time so a restart or sleeping server does not miss the whole day.
  cron.schedule('5 * * * *', runBillGenerationJob, { timezone: BILLING_TIMEZONE })
}
