import cron from 'node-cron'
import Tenant from '../models/Tenant.model.js'
import Bill from '../models/Bill.model.js'
import LandlordProfile from '../models/LandlordProfile.model.js'
import { sendBillReadyNotification } from '../services/notification.service.js'
import { getPlanConfig } from '../utils/plans.js'

// Runs at 00:05 every day — checks if today is a landlord's bill generation day
cron.schedule('5 0 * * *', async () => {
  const today = new Date()
  const dayOfMonth = today.getDate()
  const year = today.getFullYear()
  const month = `${year}-${String(today.getMonth() + 1).padStart(2, '0')}`

  console.log(`⏰ Auto bill check — day ${dayOfMonth}, month ${month}`)

  try {
    // Find landlords whose generation day matches today
    const profiles = await LandlordProfile.find({ billGenerationDay: dayOfMonth })
    if (profiles.length === 0) return

    let totalCreated = 0, totalSkipped = 0

    for (const profile of profiles) {
      const plan = await getPlanConfig(profile.plan)
      if (!plan.autoBill) continue

      const landlordId = profile.userId
      const dueDateDay = dayOfMonth + (profile.billDueDays || 10)
      const dueDate = new Date(year, today.getMonth(), Math.min(dueDateDay, 28))

      const tenants = await Tenant.find({ landlordId, isActive: true }).populate('propertyId').populate('userId')

      for (const tenant of tenants) {
        const existing = await Bill.findOne({ tenantId: tenant._id, month })
        if (existing) { totalSkipped++; continue }

        const rentAmount = tenant.monthlyRent || tenant.propertyId?.monthlyRent || 0
        const items = [{ type: 'rent', amount: rentAmount }]

        // Add utility defaults if set
        const ud = tenant.utilityDefaults || {}
        if (ud.gasAmount > 0)       items.push({ type: 'gas',         label: 'গ্যাস বিল',     amount: ud.gasAmount })
        if (ud.waterAmount > 0)     items.push({ type: 'water',       label: 'পানির বিল',     amount: ud.waterAmount })
        if (ud.serviceCharge > 0)   items.push({ type: 'maintenance', label: 'সার্ভিস চার্জ', amount: ud.serviceCharge })
        if (ud.garbageAmount > 0)   items.push({ type: 'garbage',     label: 'ময়লার বিল',     amount: ud.garbageAmount })
        if (ud.electricityAmount > 0) items.push({ type: 'electricity', label: 'বিদ্যুৎ বিল', amount: ud.electricityAmount })

        const totalAmount = items.reduce((s, i) => s + i.amount, 0)

        const bill = await Bill.create({
          landlordId,
          tenantId: tenant._id,
          propertyId: tenant.propertyId._id,
          month, year,
          items, totalAmount,
          dueAmount: totalAmount,
          dueDate,
          isAutoGenerated: true,
        })

        await sendBillReadyNotification(tenant, bill)
        totalCreated++
      }
    }

    console.log(`✅ Auto bill generation done — Created: ${totalCreated}, Skipped: ${totalSkipped}`)
  } catch (err) {
    console.error('❌ Bill generation job failed:', err.message)
  }
})
