import cron from 'node-cron'
import Tenant from '../models/Tenant.model.js'
import Bill from '../models/Bill.model.js'
import { sendBillReadyNotification } from '../services/notification.service.js'

// Runs at 00:01 on the 1st of every month
cron.schedule('1 0 1 * *', async () => {
  console.log('⏰ Running monthly bill generation job...')

  const now    = new Date()
  const year   = now.getFullYear()
  const month  = `${year}-${String(now.getMonth() + 1).padStart(2, '0')}`
  const dueDate = new Date(year, now.getMonth(), 10)   // 10th of current month

  try {
    const tenants = await Tenant.find({ isActive: true })
      .populate('propertyId')
      .populate('userId')

    let created = 0
    let skipped = 0

    for (const tenant of tenants) {
      const existing = await Bill.findOne({ tenantId: tenant._id, month })
      if (existing) { skipped++; continue }

      const rentAmount = tenant.monthlyRent || tenant.propertyId?.monthlyRent || 0

      const bill = await Bill.create({
        landlordId:      tenant.landlordId,
        tenantId:        tenant._id,
        propertyId:      tenant.propertyId._id,
        month,
        year,
        items:           [{ type: 'rent', amount: rentAmount }],
        totalAmount:     rentAmount,
        dueAmount:       rentAmount,
        dueDate,
        isAutoGenerated: true,
      })

      await sendBillReadyNotification(tenant, bill)
      created++
    }

    console.log(`✅ Bill generation done — Created: ${created}, Skipped: ${skipped}`)
  } catch (err) {
    console.error('❌ Bill generation job failed:', err.message)
  }
})
