import mongoose from 'mongoose'

const billItemSchema = new mongoose.Schema({
  type:   { type: String, enum: ['rent','electricity','gas','water','garbage','internet','maintenance','custom'], required: true },
  label:  { type: String },
  amount: { type: Number, required: true },
}, { _id: false })

const billSchema = new mongoose.Schema({
  landlordId:      { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  tenantId:        { type: mongoose.Schema.Types.ObjectId, ref: 'Tenant', required: true },
  propertyId:      { type: mongoose.Schema.Types.ObjectId, ref: 'Property', required: true },
  month:           { type: String, required: true },   // "2025-01"
  year:            { type: Number, required: true },
  items:           [billItemSchema],
  totalAmount:     { type: Number, required: true },
  paidAmount:      { type: Number, default: 0 },
  dueAmount:       { type: Number, required: true },
  status:          { type: String, enum: ['unpaid', 'partial', 'paid'], default: 'unpaid' },
  dueDate:         { type: Date },
  isAutoGenerated: { type: Boolean, default: false },
  notes:           { type: String },
}, { timestamps: true })

billSchema.index({ landlordId: 1, month: 1 })
billSchema.index({ tenantId: 1, status: 1 })

export default mongoose.model('Bill', billSchema)
